### ISSUE TITLE
Ferocious.exe - System error

### ISSUE THREAD

**Issue by Barough** [jniemann66/ferocious#1]
Getting an Ferocious.exe - System error saying that it cant start the program due to that libgcc_s_dw2-1.dll is missing on the computer. The file in question is NOT included in the zip archives at all.

**Comment by jniemann66** [comment]
Rightio - I was relying on Qt's windeployqt.exe tool to resolve the dependencies, but it looks like it hasn't included this one. I need to test on a PC without Qt installed, and I'll sort out this and any other missing dlls ... thanks for letting me know

**Comment by Barough** [comment]
Your welcome :)

**Comment by jniemann66** [comment]
OK - I think I've worked it out now.
It was a bit more involved than I was expecting.
I think the main issue was that the deployment tool was copying the wrong compiler runtimes (ie my system copy of mingw / gcc instead of Qt's copy).

I have updated the release and the master branch. The zip files should each be around 12MB now (instead of 20+ MB). I also removed the huge D3D and OpenGL dlls (despite qt deployment tool insisting that they are needed.).

Anyway -  let me know if it works now.

**Comment by Barough** [comment]
Just had a quick test with  the updated release and no error(s) when starting Ferocious. :)

**Comment by jniemann66** [comment]
Cool - Ok to close now ?

I'm just going to keep some notes here for future reference:

use the **--no-compiler-runtime** option of windeployqt.exe and copy the compiler dlls manually from the relevant kit's bin folder.

[QTBUG-46458](https://bugreports.qt.io/browse/QTBUG-46458)
[qt windows deployment docs](http://doc.qt.io/qt-5/windows-deployment.html)
