### ISSUE TITLE
Cannot convert CAF to WAV file

### ISSUE THREAD

**Issue by ghost** [jniemann66/ferocious#5]
Hello,

I'm getting this error when trying to convert cat to wav

`2.0.8 64-bit version Input file: C:\Users\Castle\Samples\Apple\01 Hip Hop\Abandoned Brass Stabs.caf Output file: C:\Users\Castle\Samples\Apple\01 Hip Hop\Abandoned Brass Stabs(converted).wav  Changing output bit format to 24 Changing output file format to wav 
Error: Couldn't Open Input File (Supported file format but unsupported encoding.) `

**Comment by jniemann66** [comment]
Hi There.

Ferocious / ReSampler uses the [libsndfile](http://www.mega-nerd.com/libsndfile/) library to read and write the various audio formats, and I think in the case of .caf files, only the standard PCM formats are supported.

It looks like your file might have an encoding other than PCM (possibly AAC or some other sort of compressed encoding).

Unfortunately, I think you're out of luck with this one. Sorry.

On a Mac, the coreaudio library could be used to decode it. 
I have heard of people getting coreAudio to run on Windows, because the library is installed as part of itunes iirc. 
However, on Linux, I don't think it's looking too good.

I might do a bit of investigation and see what other libraries / decoders are available for decoding caf files, but I can't really promise anything.

Regards
Judd

**Comment by jniemann66** [comment]
Looks like [qaac](https://sites.google.com/site/qaacpage/) might be able to open the caf files.
But, this would still require Quicktime or iTunes to be installed first - there's no getting around that.
I might be able to write a converter definition to enable ferocious to read .caf files via qaac.

**Comment by ghost** [comment]
Understood!
